services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - '5433:5432'
    env_file:
      - ./.env
    volumes:
      - postgres:/bitnami/postgresql
    networks:
      - network
    restart: always
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - ./.env
    volumes:
      - 'redis:/bitnami/redis/data'
    networks:
      - network
    restart: always
  # api:
  #   image: api
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   expose:
  #     - 3000
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./.env
  #   networks:
  #     - network
  #   depends_on:
  #     - postgres
  #     - redis

volumes:
  postgres:
  redis:

networks:
  network:
    driver: bridge